// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ano-ui/components/AButton/AButton.vue')['AButton']
    ANotify: typeof import('ano-ui/components/ANotify/ANotify.vue')['ANotify']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UBasePage: typeof import('./components/UnoUI/UBasePage/UBasePage.vue')['default']
  }
}
